### PR TITLE
add jellyfish topology

### PR DESCRIPTION
**Pull request by mananpoddar**
I have not solely contributed to this module. I had done this project with two of my friends under prof. Mohit Tahiliani. Please see [this]( qhttps://github.com/mananpoddar/Implementation-of-Jellyfish-in-ns3) link to see the original contributions/contributors.

### CODE REVIEW

**Comment by msagarpatel** [comment]
As stated in the description of this repo, ns-3 has moved to [GitLab](https://gitlab.com/nsnam/ns-3-dev). Close this PR, and submit your merge request on GitLab.

I haven't reviewed your code, but you shouldn't submit anything in `./scratch/`. If those are examples, they go in `./examples/point-to-point-layout/`.

Finally, we can't see the link in your comment.

**Comment by mananpoddar** [comment]
sir, 
[link to the original repo](https://github.com/mananpoddar/Implementation-of-Jellyfish-in-ns3)
I may not be able to close the PR for a while because I have mentioned this PR on my GSoC proposal. Though, I will try to make the code of topology as per the ns-3 standard directory structure and will submit an MR on GitLab. Thanks for the suggestions.

**Comment by msagarpatel** [comment]
No worries. Thanks, and good luck!

**Comment by tomhenderson** [comment]
Closing (please submit future PRs to GitLab.com as Merge Requests).

**Pull request closed without merging**
